name: salt-electron

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
    Build Windows:
        runs-on: windows-latest

        steps:
            - name: Checkout Source
              uses: actions/checkout@v2

            - name: Install Node
            uses: actions/setup-node@v2

            - name: Install node packages
              run: npm install

            - name: Make with Electron Builder
              run: npm run make-win

            - name: Upload Windows Executable
              uses: actions/upload-artifact@v2
              if: matrix.os == 'windows-latest'
              with:
              name: Windows x64
              path: ./dist/squirrel-windows/Salt-*.exe


    Build Linux:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source
              uses: actions/checkout@v2

            - name: Install Node
              uses: actions/setup-node@v2

            - name: Install node packages
              run: npm install

            - name: Make with Electron Builder
              run: npm run make-lin

            - name: Upload Linux AppImage
              uses: actions/upload-artifact@v2
              if: matrix.os == 'ubuntu-latest'
              with:
              name: Linux AppImage
              path: ./dist/Salt-*.AppImage
