name: salt-electron

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    Build-Windows:
        runs-on: windows-latest

        steps:
          - name: Checkout Source
            uses: actions/checkout@v2

          - name: Install Node
            uses: actions/setup-node@v2
            with:
                node-version: '16'

          - name: Install node packages for Electron
            run: npm install

          - name: Install node packages for React
            run: npm install
            working-directory: ./web

          - name: Build React UI
            run: node buildWeb

          - name: Make with Electron Builder
            run: npm run make-win
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Upload Windows Executable
            uses: actions/upload-artifact@v2
            with:
                name: Windows x64
                path: ./build/squirrel-windows/Salt Manager Setup*.exe


    Build-Linux:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Source
            uses: actions/checkout@v2

          - name: Install Node
            uses: actions/setup-node@v2
            with:
                node-version: '16'

          - name: Install node packages for Electron
            run: npm install

          - name: Install node packages for React
            run: npm install
            working-directory: ./web

          - name: Build React UI
            run: node buildWeb

          - name: Make with Electron Builder
            run: npm run make-lin
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Upload Linux AppImage
            uses: actions/upload-artifact@v2
            with:
                name: Linux AppImage
                path: ./build/Salt Manager-*.AppImage

          - name: Upload Linux tar.gz
            uses: actions/upload-artifact@v2
            with:
                name: Linux tar.gz
                path: ./build/salt-electron-*.tar.gz


    Build-MacOS:
        runs-on: macos-latest

        steps:
          - name: Checkout Source
            uses: actions/checkout@v2

          - name: Install Node
            uses: actions/setup-node@v2
            with:
                node-version: '16'

          - name: Install node packages for Electron
            run: npm install

          - name: Install node packages for React
            run: npm install
            working-directory: ./web

          - name: Build React UI
            run: node buildWeb

          - name: Make with Electron Builder
            run: npm run make-mac
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          - name: Upload MacOS DMG
            uses: actions/upload-artifact@v2
            with:
                name: MacOS DMG
                path: ./build/Salt Manager-*.dmg

          - name: Upload MacOS .app
            uses: actions/upload-artifact@v2
            with:
                name: MacOS .app
                path: ./build/Salt Manager-*.zip